name: Xenosaga
sha1: fd206d5715a322830f7fa9285fb4a09276ac2a63
options:
  # paths
  basename: SLUS_204.69
  target_path: iso/SLUS_204.69
  base_path: ..

  asm_path: asm
  src_path: src
  build_path: build

  extensions_path: tools/splat_ext
  symbol_addrs_path: config/symbol_addrs.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.txt
  undefined_syms_auto_path: config/undefined_syms_auto.txt

  # compiler
  compiler: EEGCC
  platform: ps2

  string_encoding: ASCII
  rodata_string_guesser_level: 2 # improve string detection
  disasm_unknown: True
  named_regs_for_c_funcs: False
  gp_value: 0x4dfb70

  find_file_boundaries: False
  section_order:
    [".text", ".data", ".rodata", ".lit4", ".sdata", ".sbss", ".bss"]
segments:
  - [0, databin, elf_header]
  - name: main
    type: code
    start: 0x1000
    vram: 0x200000
    bss_size: 0x4C1090
    subalign: 4
    subsegments:
      # .text
      - [0x1000, asm]
      - [0x7bc78, c, eMessage]
      - [0x7cf40, asm]

      - [0x139570, databin] # .reginfo

      # .data
      - [0x139600, data]
      - [0x16d370, data, eMessage]
      - [0x16d390, data]

      - [0x2aee54, databin] #.ctors
      - [0x2aee5c, databin] #.dtors
      - [0x2aee68, databin] #.eh_frame

      # .vudata
      - [0x2aee70, databin]

      # .rodata
      - [0x2bf280, rodata, 1000]
      - [0x2c47d0, rodata, 7CF40]

      # .lit4
      - [0x2d8b80, lit4] 

      # .sdata
      - [0x2d9a00, sdata]
      - [0x2db918, sdata, eMessage]
      - [0x2db930, sdata]

      # .sbss
      - {start: 0x2dd500, type: sbss, vram: 0x4dc500}
      # .bss
      - {start: 0x2dd56c, type: bss, vram: 0x4dc880}
  - [0x2dd500, databin] # padding
  - [0x2f18ec, databin] # overlay stuff?
  - [0x3021af, databin] # .shstrtab
  - [0x303058, databin] # .symtab
  - [0x329c98, databin] # strtab
  - [0x34850C] #end of file
