name: Xenosaga
sha1: fd206d5715a322830f7fa9285fb4a09276ac2a63
options:
  # paths
  basename: SLUS_204.69
  target_path: iso/SLUS_204.69
  base_path: ..

  asm_path: asm
  src_path: src
  build_path: build

  extensions_path: tools/splat_ext
  symbol_addrs_path: config/symbol_addrs.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.txt
  undefined_syms_auto_path: config/undefined_syms_auto.txt

  # compiler
  compiler: EEGCC
  platform: ps2

  #ld_bss_contains_common: True

  string_encoding: ASCII
  rodata_string_guesser_level: 2 # improve string detection
  disasm_unknown: True
  named_regs_for_c_funcs: False
  gp_value: 0x4dfb70
  # subalign: 4
  #include_macro_inc: no # don't write macro.inc to rodata files

  find_file_boundaries: True
  section_order:
    [".text", ".data", ".rodata", ".lit4", ".sdata", ".sbss", ".bss"]
segments:
  - [0, databin, elf_header]
  - name: main
    type: code
    start: 0x1000
    vram: 0x200000
    bss_size: 0x4C13a4
    subalign: null
    subsegments:
      # .text
      - [0x1000, asm, text]

      # .vutext
      - [0x139570, data, vutext]

      - [0x139570, databin] # .reginfo

      # .data
      - [0x139600, data, data]

      - [0x2aee54, databin] #.ctors
      - [0x2aee5c, databin] #.dtors
      - [0x2aee68, databin] #.eh_frame

      # .vudata
      - [0x2aee70, data, vudata]

      # .rodata
      - [0x2bf280, rodata, rodata]

      # .lit4
      - [0x2d8b80, lit4] 

      # .sdata
      - [0x2d9a00, sdata, sdata]

      # .sbss
      - [0x2dd500, sbss, sbss]

      # .vubss
      - [0x2dd56c, data, vubss]

      # .bss
      - [0x2dd56c, bss, bss]
      
  - [0x2f18ec, databin] # overlay stuff?
  - [0x3021af, databin] # .shstrtab
  - [0x303058, databin] # .symtab
  - [0x329c98, databin] # strtab
  - [0x34850C] #end of file
