name: Xenosaga
sha1: fd206d5715a322830f7fa9285fb4a09276ac2a63
options:
  # paths
  basename: SLUS_204.69
  target_path: iso/SLUS_204.69
  base_path: ..
  asm_path: asm
  src_path: src
  build_path: build
  undefined_funcs_auto_path: config/undefined_funcs_auto.txt
  undefined_syms_auto_path: config/undefined_syms_auto.txt
  symbol_addrs_path: config/symbol_addrs.txt

  # compiler
  compiler: EEGCC
  platform: ps2

  gp_value: 0x4dfb70
  use_legacy_include_asm: False
  named_regs_for_c_funcs: False
  disasm_unknown: True

  string_encoding: ASCII
  rodata_string_guesser_level: 2 # improve string detection

  # find_file_boundaries: False
  section_order:
    [".text", ".data", ".rodata", ".lit4", ".sdata", ".sbss", ".bss"]
segments:
  - [0, databin, elf_header]
  - name: main
    type: code
    start: 0x1000
    vram: 0x200000
    bss_size: 0x4C1090
    subalign: 4
    subsegments:
      # .text
      - [0x1000, asm]
      - [0x19a0, asm]
      - [0x1d70, asm]
      - [0x1ff0, asm]
      - [0x2350, asm]
      - [0x26b0, asm]
      - [0x2890, asm]
      - [0x2db0, asm]
      - [0x3728, asm]
      - [0x3e70, asm]
      - [0x4dd0, asm]
      - [0x8468, asm]
      - [0x8768, asm]
      - [0x94c8, asm]
      - [0x9778, asm]
      - [0x9fe0, asm]
      - [0xa040, asm]
      - [0xa180, asm]
      - [0xa300, asm]
      - [0xa410, asm]
      - [0xa5b0, asm]
      - [0xa618, asm]
      - [0xa888, asm]
      - [0xa948, asm]
      - [0xaa10, asm]
      - [0xabf8, asm]
      - [0xace0, asm]
      - [0xad78, asm]
      - [0xb090, asm]
      - [0xb278, asm]
      - [0xb3b8, asm]
      - [0xb538, asm]
      - [0xbbc8, asm]
      - [0xbc68, asm]
      - [0xbc78, asm]
      - [0xbc88, asm]
      - [0xbce0, asm]
      - [0xbcf8, asm]
      - [0xbd50, asm]
      - [0xbde8, asm]
      - [0xbe40, asm]
      - [0xbed0, asm]
      - [0xbf28, asm]
      - [0xbf80, asm]
      - [0xbfb0, asm]
      - [0xbfc8, asm]
      - [0xc070, asm]
      - [0xc088, asm]
      - [0xc108, asm]
      - [0xc120, asm]
      - [0xc160, asm]
      - [0xc1b0, asm]
      - [0xc1d8, asm]
      - [0xc208, asm]
      - [0xc3f0, asm]
      - [0xc448, asm]
      - [0xc478, asm]
      - [0xc4f0, asm]
      - [0xc568, asm]
      - [0xc580, asm]
      - [0xd918, asm]
      - [0xec68, asm]
      - [0xec98, asm]
      - [0xee78, asm]
      - [0xef28, asm]
      - [0xefc0, asm]
      - [0xf058, asm]
      - [0xf110, asm]
      - [0xf1c8, asm]
      - [0xf358, asm]
      - [0xf410, asm]
      - [0xf508, asm]
      - [0xf9e8, asm]
      - [0x111a0, asm]
      - [0x11510, asm]
      - [0x117b0, asm]
      - [0x16410, asm]
      - [0x16bd0, asm]
      - [0x16de0, asm]
      - [0x17be8, asm]
      - [0x18738, asm]
      - [0x19220, asm]
      - [0x1923c, asm]
      - [0x19240, asm]
      - [0x194b8, asm]
      - [0x198a0, asm]
      - [0x19a68, asm]
      - [0x1c6b0, asm]
      - [0x1ca68, asm]
      - [0x1d528, asm]
      - [0x1d788, asm]
      - [0x1ded0, asm]
      - [0x20b58, asm]
      - [0x21c58, asm]
      - [0x23878, asm]
      - [0x23bd0, asm]
      - [0x242a8, asm]
      - [0x26a58, asm]
      - [0x281a0, asm]
      - [0x29c58, asm]
      - [0x2bc30, asm]
      - [0x2bec0, asm]
      - [0x2d268, asm]
      - [0x2d558, asm]
      - [0x2d8b8, asm]
      - [0x2ee28, asm]
      - [0x37448, asm]
      - [0x3b290, asm]
      - [0x3f0e0, asm]
      - [0x40960, asm]
      - [0x41478, asm]
      - [0x415e8, asm]
      - [0x422d0, asm]
      - [0x429c0, asm]
      - [0x430a8, asm]
      - [0x43668, asm]
      - [0x47098, asm]
      - [0x47428, asm]
      - [0x47918, asm]
      - [0x49ff8, asm]
      - [0x4b378, asm]
      - [0x4eaa0, asm]
      - [0x4f240, asm]
      - [0x512d0, asm]
      - [0x51cf0, asm]
      - [0x52f40, asm]
      - [0x53d50, asm]
      - [0x53fc8, asm]
      - [0x54b58, asm]
      - [0x554b8, asm]
      - [0x55760, asm]
      - [0x59010, asm]
      - [0x5a340, asm]
      - [0x5aa88, asm]
      - [0x5ac38, asm]
      - [0x5b0b0, asm]
      - [0x5b1c0, asm]
      - [0x5b210, asm]
      - [0x5b8c0, asm]
      - [0x5be20, asm]
      - [0x5c118, asm]
      - [0x5dfc8, asm]
      - [0x60ec8, asm]
      - [0x616e0, asm]
      - [0x61b90, asm]
      - [0x61d78, asm]
      - [0x620d0, asm]
      - [0x66150, asm]
      - [0x6b630, asm]
      - [0x6bc68, asm]
      - [0x6bf68, asm]
      - [0x6c130, asm]
      - [0x6ce18, asm]
      - [0x6cf80, asm]
      - [0x6e430, asm]
      - [0x6ee50, asm]
      - [0x704d8, asm]
      - [0x74d20, asm]
      - [0x75be0, asm]
      - [0x77358, asm]
      - [0x78608, asm]
      - [0x7bc78, c, eMessage]
      - [0x7cf40, c, print]
      - [0x80108, asm, MenuModel]
      - [0x829a8, asm, eBattle]
      - [0x85410, asm, File]
      - [0x8afd0, asm, MenuBattle]
      - [0x8f658, asm, MenuExtra]
      - [0x923c0, asm, MenuPara]
      - [0x9ae18, asm, Agws]
      - [0xa0440, asm, Seisan]
      - [0xa2ff0, asm, MenuShop]
      - [0xaaf10, asm, MenuEther]
      - [0xb0498, asm, MenuTec]
      - [0xb5128, asm, MenuSystem]
      - [0xb66c0, asm, PartyData]
      - [0xb79e8, asm, MenuSkill]
      - [0xbaf10, asm, EtherTree]
      - [0xbdaf8, asm, DataBox]
      - [0xbde98, asm, test/KarakamaTest]
      - [0xbefb8, asm, UwamonoSys]
      - [0xc5760, asm, MapDoor]
      - [0xc68d0, asm, MapTrap]
      - [0xc7388, asm, Item]
      - [0xc88d0, asm, Disp]
      - [0xc9970, asm, VectorMath]
      - [0xc9f10, asm, Drill]
      - [0xcc1a8, c, test/Matumoto]
      - [0xcc1b0, asm, Enemy]
      - [0xcf7f0, asm, Ladder]
      - [0xd1488, asm, EnemySound]
      - [0xd3d50, asm, EnemyCommand]
      - [0xd4828, asm, EnemyActionReady]
      - [0xd4e18, asm, EnemySystem]
      - [0xd5450, asm, PauseMenuPageEnemy]
      - [0xd71a8, asm, EventCheck]
      - [0xd7aa8, asm, CheckActor]
      - [0xd7c60, asm, Vibration]
      - [0xd7da0, asm]
      - [0xda100, asm]
      - [0xda2e0, asm]
      - [0xda430, asm]
      - [0xdb1d8, asm]
      - [0xdc6b8, asm]
      - [0xdd3a8, asm]
      - [0xdd410, asm]
      - [0xdea70, asm]
      - [0xdeaf8, asm]
      - [0xe2000, asm]
      - [0xe9040, asm]
      - [0xeab28, asm]
      - [0xecd90, asm]
      - [0xed310, asm]
      - [0xefc50, asm]
      - [0xefebc, asm]
      - [0xefec0, asm]
      - [0xeffe0, asm]
      - [0xf1018, asm]
      - [0xf12c0, asm]
      - [0xf1c64, asm]
      - [0xf1c68, asm]
      - [0xf2708, asm]
      - [0xf2b00, asm]
      - [0xf2d98, asm]
      - [0xf5528, asm]
      - [0xf6998, asm]
      - [0xf6d10, asm]
      - [0xf6f70, asm]
      - [0xf7130, asm]
      - [0xf7550, asm]
      - [0xf7650, asm]
      - [0xf7708, asm]
      - [0xf7810, asm]
      - [0xf7a58, asm]
      - [0xf7c50, asm]
      - [0xf8200, asm]
      - [0xf97b0, asm]
      - [0xf9aa0, asm]
      - [0xf9c20, asm]
      - [0xfb030, asm]
      - [0xfb228, asm]
      - [0xfb3a8, asm]
      - [0xfb678, asm]
      - [0xfc390, asm]
      - [0xfd980, asm]
      - [0xfdcf0, asm]
      - [0x102400, asm]
      - [0x105d40, asm]
      - [0x105d70, asm]
      - [0x106444, asm]
      - [0x106448, asm]
      - [0x106998, asm]
      - [0x107578, asm]
      - [0x109618, asm]
      - [0x10a488, asm]
      - [0x10c970, asm]
      - [0x10d6e0, asm]
      - [0x10ec08, asm]
      - [0x10fc08, asm]
      - [0x116958, asm]
      - [0x118060, asm]
      - [0x118ce0, asm]
      - [0x119150, asm]
      - [0x11b190, asm]
      - [0x11f8c8, asm]
      - [0x11fde0, asm]
      - [0x120548, asm]
      - [0x1221a0, asm]
      - [0x122be0, asm]
      - [0x122ce8, asm]
      - [0x124ab0, asm]
      - [0x124bd8, asm]
      - [0x124d10, asm]
      - [0x124de8, asm]
      - [0x124ed8, asm]
      - [0x124fc0, asm]
      - [0x125038, asm]
      - [0x125050, asm]
      - [0x125068, asm]
      - [0x125080, asm]
      - [0x125098, asm]
      - [0x1250b0, asm]
      - [0x1250c8, asm]
      - [0x1250e0, asm]
      - [0x1250f8, asm]
      - [0x125110, asm]
      - [0x125838, asm]
      - [0x125b78, asm]
      - [0x125f98, asm]
      - [0x126ef0, asm]
      - [0x1274a8, asm]
      - [0x1277c8, asm]
      - [0x127b80, asm]
      - [0x127d68, asm]
      - [0x127f38, asm]
      - [0x128300, asm]
      - [0x1283d8, asm]
      - [0x1286b0, asm]
      - [0x129200, asm]
      - [0x129438, asm]
      - [0x1295a8, asm]
      - [0x129e50, asm]
      - [0x129f78, asm]
      - [0x12a220, asm]
      - [0x12a6e8, asm]
      - [0x12a720, asm]
      - [0x12a938, asm]
      - [0x12ab20, asm]
      - [0x12adc0, asm]
      - [0x12ade8, asm]
      - [0x12aeb0, asm]
      - [0x12aef8, asm]
      - [0x12af38, asm]
      - [0x12afb0, asm]
      - [0x12b648, asm]
      - [0x12bcd8, asm]
      - [0x12c258, asm]
      - [0x12c7c0, asm]
      - [0x12c8d8, asm]
      - [0x12ca00, asm]
      - [0x12cb88, asm]
      - [0x12cbc8, asm]
      - [0x12cee8, asm]
      - [0x12d198, asm]
      - [0x12d310, asm]
      - [0x12d360, asm]
      - [0x12d418, asm]
      - [0x12d4b8, asm]
      - [0x12d4e8, asm]
      - [0x12d53c, asm]
      - [0x12d540, asm]
      - [0x12d5e0, asm]
      - [0x12eb50, asm]
      - [0x12ebf8, asm]
      - [0x12ec58, asm]
      - [0x12ec88, asm]
      - [0x12eda0, asm]
      - [0x12ee50, asm]
      - [0x12ef70, asm]
      - [0x12f040, asm]
      - [0x12f058, asm]
      - [0x12f0f8, asm]
      - [0x12f110, asm]
      - [0x12f138, asm]
      - [0x12f158, asm]
      - [0x12f168, asm]
      - [0x12f214, asm]
      - [0x12f218, asm]
      - [0x12f2b8, asm]
      - [0x12ff40, asm]
      - [0x130010, asm]
      - [0x1300e0, asm]
      - [0x130160, asm]
      - [0x1301b8, asm]
      - [0x1304a0, asm]
      - [0x130518, asm]
      - [0x130630, asm]
      - [0x1306e0, asm]
      - [0x130e08, asm]
      - [0x1311d0, asm]
      - [0x131220, asm]
      - [0x1312a8, asm]
      - [0x132210, asm]
      - [0x132478, asm]
      - [0x133ef0, asm]
      - [0x134c80, asm]
      - [0x134ca8, asm]
      - [0x134d58, asm]
      - [0x134e68, asm]
      - [0x134e84, asm]
      - [0x134e88, asm]
      - [0x136320, asm]
      - [0x136438, asm]
      - [0x1366d8, asm]
      - [0x1367f8, asm]
      - [0x136c60, asm]
      - [0x137040, asm]
      - [0x1370d8, asm]
      - [0x1371c0, asm]
      - [0x137318, asm]
      - [0x137430, asm]
      - [0x138448, asm]
      - [0x1385fc, asm]
      - [0x138600, asm]
      - [0x138648, asm]
      - [0x138688, asm]
      - [0x1387f8, asm]
      - [0x138a58, asm]
      - [0x138cc8, asm]
      - [0x138d28, asm]
      - [0x138de0, asm]
      - [0x138e38, asm]
      - [0x138e98, asm]
      - [0x138ef8, asm]
      - [0x138f58, asm]
      - [0x1394f8, asm]

      - [0x139570, databin] # .reginfo

      # .data
      - [0x139600, data]
      - [0x16d370, data, eMessage]
      - [0x16d390, data]

      - [0x2aee54, databin] #.ctors
      - [0x2aee5c, databin] #.dtors
      - [0x2aee68, databin] #.eh_frame

      # .vudata
      - [0x2aee70, databin]

      # .rodata
      - [0x2bf280, rodata]
      # - [0x2c47d0, rodata, MenuModel]

      # .lit4
      - [0x2d8b80, lit4] 

      # .sdata
      - [0x2d9a00, sdata]
      - [0x2db918, sdata, eMessage]
      - [0x2db930, sdata]

      # .sbss
      - {start: 0x2dd500, type: sbss, vram: 0x4dc500}
      # .bss
      - {start: 0x2dd56c, type: bss, vram: 0x4dc880}
  - [0x2dd500, databin] # padding
  - [0x2f18ec, databin] # overlay stuff?
  - [0x3021af, databin] # .shstrtab
  - [0x303058, databin] # .symtab
  - [0x329c98, databin] # strtab
  - [0x34850C] #end of file
