name: Build

on:
  push:
  pull_request:

jobs:
  build:
    container: ghcr.io/SquareMan/xenosaga-build:main

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      # Checkout the repository (shallow clone)
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      # Set Git config
      - name: Git config
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      # Copy the original files to the workspace
      - name: Prepare
        run: cp -R /orig/* ./iso

      # Install python requirements
      - name: Python dependencies
        run: pip install -r requirements.txt

      # Build the project
      - name: Build
        run: |
          python configure.py 
          ninja
